# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AuthService.proto',
  package='deal',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x41uthService.proto\x12\x04\x64\x65\x61l\"\x07\n\x05\x45mpty\"0\n\rSignInRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x8f\x01\n\rSignUpRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x16\n\x0e\x61greeWithTerms\x18\x03 \x01(\x08\x12\x1f\n\x04type\x18\x04 \x01(\x0e\x32\x11.deal.AccountType\x12$\n\x08platform\x18\x05 \x01(\x0e\x32\x12.deal.PlatformType\"E\n\x0c\x43ommonResult\x12$\n\nresultCode\x18\x01 \x01(\x0e\x32\x10.deal.ResultCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\tJWTResult\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.deal.JWTType\x12\r\n\x05token\x18\x02 \x01(\t\"R\n\x0eSignInResponse\x12\"\n\x06result\x18\x01 \x01(\x0b\x32\x12.deal.CommonResult\x12\x1c\n\x03jwt\x18\x02 \x03(\x0b\x32\x0f.deal.JWTResult\"R\n\x0eSignUpResponse\x12\"\n\x06result\x18\x01 \x01(\x0b\x32\x12.deal.CommonResult\x12\x1c\n\x03jwt\x18\x02 \x03(\x0b\x32\x0f.deal.JWTResult*:\n\x0cPlatformType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x41NDROID\x10\x01\x12\x07\n\x03IOS\x10\x02\x12\x07\n\x03WEB\x10\x03*$\n\x0b\x41\x63\x63ountType\x12\t\n\x05\x45MAIL\x10\x00\x12\n\n\x06GOOGLE\x10\x01*\"\n\x07JWTType\x12\n\n\x06\x41\x43\x43\x45SS\x10\x00\x12\x0b\n\x07REFRESH\x10\x01*$\n\nResultCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\xbb\x01\n\x0b\x41uthService\x12\x41\n\x14signInWithCredential\x12\x13.deal.SignInRequest\x1a\x14.deal.SignInResponse\x12\x34\n\x0fsignInWithToken\x12\x0b.deal.Empty\x1a\x14.deal.SignInResponse\x12\x33\n\x06signUp\x12\x13.deal.SignUpRequest\x1a\x14.deal.SignUpResponseb\x06proto3')
)

_PLATFORMTYPE = _descriptor.EnumDescriptor(
  name='PlatformType',
  full_name='deal.PlatformType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANDROID', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IOS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEB', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=528,
  serialized_end=586,
)
_sym_db.RegisterEnumDescriptor(_PLATFORMTYPE)

PlatformType = enum_type_wrapper.EnumTypeWrapper(_PLATFORMTYPE)
_ACCOUNTTYPE = _descriptor.EnumDescriptor(
  name='AccountType',
  full_name='deal.AccountType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMAIL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOOGLE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=588,
  serialized_end=624,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTTYPE)

AccountType = enum_type_wrapper.EnumTypeWrapper(_ACCOUNTTYPE)
_JWTTYPE = _descriptor.EnumDescriptor(
  name='JWTType',
  full_name='deal.JWTType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REFRESH', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=626,
  serialized_end=660,
)
_sym_db.RegisterEnumDescriptor(_JWTTYPE)

JWTType = enum_type_wrapper.EnumTypeWrapper(_JWTTYPE)
_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='deal.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=662,
  serialized_end=698,
)
_sym_db.RegisterEnumDescriptor(_RESULTCODE)

ResultCode = enum_type_wrapper.EnumTypeWrapper(_RESULTCODE)
UNKNOWN = 0
ANDROID = 1
IOS = 2
WEB = 3
EMAIL = 0
GOOGLE = 1
ACCESS = 0
REFRESH = 1
SUCCESS = 0
ERROR = 1



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='deal.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=34,
)


_SIGNINREQUEST = _descriptor.Descriptor(
  name='SignInRequest',
  full_name='deal.SignInRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='deal.SignInRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='deal.SignInRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=84,
)


_SIGNUPREQUEST = _descriptor.Descriptor(
  name='SignUpRequest',
  full_name='deal.SignUpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='deal.SignUpRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='deal.SignUpRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agreeWithTerms', full_name='deal.SignUpRequest.agreeWithTerms', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='deal.SignUpRequest.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='deal.SignUpRequest.platform', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=230,
)


_COMMONRESULT = _descriptor.Descriptor(
  name='CommonResult',
  full_name='deal.CommonResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultCode', full_name='deal.CommonResult.resultCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='deal.CommonResult.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=301,
)


_JWTRESULT = _descriptor.Descriptor(
  name='JWTResult',
  full_name='deal.JWTResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='deal.JWTResult.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='deal.JWTResult.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=358,
)


_SIGNINRESPONSE = _descriptor.Descriptor(
  name='SignInResponse',
  full_name='deal.SignInResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='deal.SignInResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jwt', full_name='deal.SignInResponse.jwt', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=442,
)


_SIGNUPRESPONSE = _descriptor.Descriptor(
  name='SignUpResponse',
  full_name='deal.SignUpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='deal.SignUpResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jwt', full_name='deal.SignUpResponse.jwt', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=526,
)

_SIGNUPREQUEST.fields_by_name['type'].enum_type = _ACCOUNTTYPE
_SIGNUPREQUEST.fields_by_name['platform'].enum_type = _PLATFORMTYPE
_COMMONRESULT.fields_by_name['resultCode'].enum_type = _RESULTCODE
_JWTRESULT.fields_by_name['type'].enum_type = _JWTTYPE
_SIGNINRESPONSE.fields_by_name['result'].message_type = _COMMONRESULT
_SIGNINRESPONSE.fields_by_name['jwt'].message_type = _JWTRESULT
_SIGNUPRESPONSE.fields_by_name['result'].message_type = _COMMONRESULT
_SIGNUPRESPONSE.fields_by_name['jwt'].message_type = _JWTRESULT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['SignInRequest'] = _SIGNINREQUEST
DESCRIPTOR.message_types_by_name['SignUpRequest'] = _SIGNUPREQUEST
DESCRIPTOR.message_types_by_name['CommonResult'] = _COMMONRESULT
DESCRIPTOR.message_types_by_name['JWTResult'] = _JWTRESULT
DESCRIPTOR.message_types_by_name['SignInResponse'] = _SIGNINRESPONSE
DESCRIPTOR.message_types_by_name['SignUpResponse'] = _SIGNUPRESPONSE
DESCRIPTOR.enum_types_by_name['PlatformType'] = _PLATFORMTYPE
DESCRIPTOR.enum_types_by_name['AccountType'] = _ACCOUNTTYPE
DESCRIPTOR.enum_types_by_name['JWTType'] = _JWTTYPE
DESCRIPTOR.enum_types_by_name['ResultCode'] = _RESULTCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:deal.Empty)
  ))
_sym_db.RegisterMessage(Empty)

SignInRequest = _reflection.GeneratedProtocolMessageType('SignInRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNINREQUEST,
  __module__ = 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:deal.SignInRequest)
  ))
_sym_db.RegisterMessage(SignInRequest)

SignUpRequest = _reflection.GeneratedProtocolMessageType('SignUpRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUPREQUEST,
  __module__ = 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:deal.SignUpRequest)
  ))
_sym_db.RegisterMessage(SignUpRequest)

CommonResult = _reflection.GeneratedProtocolMessageType('CommonResult', (_message.Message,), dict(
  DESCRIPTOR = _COMMONRESULT,
  __module__ = 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:deal.CommonResult)
  ))
_sym_db.RegisterMessage(CommonResult)

JWTResult = _reflection.GeneratedProtocolMessageType('JWTResult', (_message.Message,), dict(
  DESCRIPTOR = _JWTRESULT,
  __module__ = 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:deal.JWTResult)
  ))
_sym_db.RegisterMessage(JWTResult)

SignInResponse = _reflection.GeneratedProtocolMessageType('SignInResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIGNINRESPONSE,
  __module__ = 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:deal.SignInResponse)
  ))
_sym_db.RegisterMessage(SignInResponse)

SignUpResponse = _reflection.GeneratedProtocolMessageType('SignUpResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUPRESPONSE,
  __module__ = 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:deal.SignUpResponse)
  ))
_sym_db.RegisterMessage(SignUpResponse)



_AUTHSERVICE = _descriptor.ServiceDescriptor(
  name='AuthService',
  full_name='deal.AuthService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=701,
  serialized_end=888,
  methods=[
  _descriptor.MethodDescriptor(
    name='signInWithCredential',
    full_name='deal.AuthService.signInWithCredential',
    index=0,
    containing_service=None,
    input_type=_SIGNINREQUEST,
    output_type=_SIGNINRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='signInWithToken',
    full_name='deal.AuthService.signInWithToken',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SIGNINRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='signUp',
    full_name='deal.AuthService.signUp',
    index=2,
    containing_service=None,
    input_type=_SIGNUPREQUEST,
    output_type=_SIGNUPRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHSERVICE)

DESCRIPTOR.services_by_name['AuthService'] = _AUTHSERVICE

# @@protoc_insertion_point(module_scope)
