# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import AuthService_pb2 as AuthService__pb2


class AuthServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.signInWithCredential = channel.unary_unary(
        '/deal.AuthService/signInWithCredential',
        request_serializer=AuthService__pb2.SignInRequest.SerializeToString,
        response_deserializer=AuthService__pb2.SignInResponse.FromString,
        )
    self.signInWithToken = channel.unary_unary(
        '/deal.AuthService/signInWithToken',
        request_serializer=AuthService__pb2.Empty.SerializeToString,
        response_deserializer=AuthService__pb2.SignInResponse.FromString,
        )
    self.signUp = channel.unary_unary(
        '/deal.AuthService/signUp',
        request_serializer=AuthService__pb2.SignUpRequest.SerializeToString,
        response_deserializer=AuthService__pb2.SignUpResponse.FromString,
        )


class AuthServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def signInWithCredential(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def signInWithToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def signUp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'signInWithCredential': grpc.unary_unary_rpc_method_handler(
          servicer.signInWithCredential,
          request_deserializer=AuthService__pb2.SignInRequest.FromString,
          response_serializer=AuthService__pb2.SignInResponse.SerializeToString,
      ),
      'signInWithToken': grpc.unary_unary_rpc_method_handler(
          servicer.signInWithToken,
          request_deserializer=AuthService__pb2.Empty.FromString,
          response_serializer=AuthService__pb2.SignInResponse.SerializeToString,
      ),
      'signUp': grpc.unary_unary_rpc_method_handler(
          servicer.signUp,
          request_deserializer=AuthService__pb2.SignUpRequest.FromString,
          response_serializer=AuthService__pb2.SignUpResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'deal.AuthService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
